/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package classsync;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class loginjf extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public loginjf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new java.awt.Label();
        subtext = new java.awt.Label();
        colorPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        signupBtn = new javax.swing.JButton();
        studentidTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        passwordLabel = new java.awt.Label();
        subtext2 = new java.awt.Label();
        studentidLabel1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClassSync");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(850, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        welcome.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        welcome.setText("Welcome to ClassSync!");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        subtext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subtext.setEnabled(false);
        subtext.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        subtext.setForeground(new java.awt.Color(102, 102, 102));
        subtext.setText("Login to take charge of your classes");
        getContentPane().add(subtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 86, -1, -1));

        colorPanel.setBackground(new java.awt.Color(0, 102, 153));
        colorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        colorPanel.setToolTipText("");

        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsync/images/CL.png"))); // NOI18N

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(colorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        signupBtn.setBackground(new java.awt.Color(242, 242, 242));
        signupBtn.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(0, 102, 153));
        signupBtn.setText("Sign Up ");
        signupBtn.setBorder(null);
        signupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                signupBtnStateChanged(evt);
            }
        });
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        getContentPane().add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        studentidTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidTfActionPerformed(evt);
            }
        });
        getContentPane().add(studentidTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 200, -1));

        passwordTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTfActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 214, 201, -1));

        loginBtn.setBackground(new java.awt.Color(0, 102, 153));
        loginBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Log In");
        loginBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 63, 24));

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 193, -1, -1));

        subtext2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subtext2.setEnabled(false);
        subtext2.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        subtext2.setForeground(new java.awt.Color(102, 102, 102));
        subtext2.setText("Don't have an account?");
        getContentPane().add(subtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, 14));

        studentidLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        studentidLabel1.setText("Student ID");
        getContentPane().add(studentidLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentidTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidTfActionPerformed
        
    }//GEN-LAST:event_studentidTfActionPerformed

    private void passwordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTfActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // Initialize a boolean variable to track if a match is found
        boolean matched = false;
        // Get the student ID and password from the text fields
        String studentID = studentidTf.getText();
        String password = passwordTf.getText();

        try {
            // Open a FileReader to read from the "accounts.txt" file
            FileReader fr = new FileReader("accounts.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            // Read each line from the file
            while ((line = br.readLine()) != null) {
                // Check if the line matches the entered student ID and password
                if (line.equals(studentID + "\t" + password)) {
                    // Set matched to true if a match is found and exit the loop
                    matched = true;
                    break;
                }
            }
            // Close the FileReader
            fr.close();
        } catch (IOException e) {
            // Handle any IOException that occurs while reading the file
        }

        // If a match is found, proceed to the main menu
        if (matched) {
            // Close the current login window
            dispose();

            // Get the current location of the login window
            int currentX = getLocation().x;
            int currentY = getLocation().y;

            // Create a new main menu window with the student ID
            mainmenujf mainmenuFrame = null;
            try {
                mainmenuFrame = new mainmenujf(studentidTf.getText());
            } catch (IOException ex) {
                Logger.getLogger(loginjf.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Set the location of the main menu window and make it visible
            mainmenuFrame.setLocation(currentX, currentY);
            mainmenuFrame.setVisible(true);
        } else {
            // If no match is found, display an error message
            javax.swing.JOptionPane.showMessageDialog(null, "Invalid Student ID or Password. Please try again.");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed

        int currentX = getLocation().x;
        int currentY = getLocation().y;

        signupjf signupFrame = new signupjf();
        signupFrame.setLocation(currentX, currentY);
        signupFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_signupBtnActionPerformed

    private void signupBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_signupBtnStateChanged
        
    }//GEN-LAST:event_signupBtnStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logo;
    private java.awt.Label passwordLabel;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JButton signupBtn;
    private java.awt.Label studentidLabel1;
    private javax.swing.JTextField studentidTf;
    private java.awt.Label subtext;
    private java.awt.Label subtext2;
    private java.awt.Label welcome;
    // End of variables declaration//GEN-END:variables
}
