/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classsync;

import java.io.FileWriter;
import java.io.IOException;

public class mainmenujf extends javax.swing.JFrame {
    
    public String openAcc;
    /**
     * Creates new form mainMenu
     * @param studentIdTf
     * @throws java.io.IOException
     */
    public mainmenujf(String studentIdTf) throws IOException {
        initComponents();
        openAcc = studentIdTf + ".txt";
        //Create a new file with the student ID as the filename
        FileWriter fw = new FileWriter(openAcc, true);
        fw.close();
    }
    
    public String getOpenAccFilePath() {
        return openAcc;
    }

    mainmenujf() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mSignOutBtn = new javax.swing.JButton();
        mViewCoursesBtn = new javax.swing.JButton();
        mSearchCoursesBtn = new javax.swing.JButton();
        mEditCourseBtn = new javax.swing.JButton();
        mInputCourseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClassSync");
        setBackground(new java.awt.Color(0, 102, 153));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(823, 314));
        setPreferredSize(new java.awt.Dimension(850, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsync/images/CL (2).png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, 80));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsync/images/Yellow Simple Quote Facebook Post (1).png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setIconTextGap(0);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, Short.MAX_VALUE)
                .addGap(213, 213, 213))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 650, 420));

        mSignOutBtn.setBackground(new java.awt.Color(242, 242, 242));
        mSignOutBtn.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        mSignOutBtn.setForeground(new java.awt.Color(0, 102, 153));
        mSignOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsync/images/Untitled design (1).png"))); // NOI18N
        mSignOutBtn.setBorder(null);
        mSignOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mSignOutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mSignOutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mSignOutBtn.setIconTextGap(0);
        mSignOutBtn.setLabel("Sign Out");
        mSignOutBtn.setMargin(new java.awt.Insets(1, 10, 1, 10));
        mSignOutBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mSignOutBtnStateChanged(evt);
            }
        });
        mSignOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSignOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mSignOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, 20));
        mSignOutBtn.getAccessibleContext().setAccessibleDescription("");

        mViewCoursesBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        mViewCoursesBtn.setForeground(new java.awt.Color(0, 102, 153));
        mViewCoursesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsync/images/3.png"))); // NOI18N
        mViewCoursesBtn.setText("View Courses");
        mViewCoursesBtn.setAlignmentY(0.0F);
        mViewCoursesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mViewCoursesBtn.setFocusCycleRoot(true);
        mViewCoursesBtn.setIconTextGap(0);
        mViewCoursesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mViewCoursesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mViewCoursesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 175, 28));

        mSearchCoursesBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        mSearchCoursesBtn.setForeground(new java.awt.Color(0, 102, 153));
        mSearchCoursesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsync/images/4.png"))); // NOI18N
        mSearchCoursesBtn.setText("Search Course");
        mSearchCoursesBtn.setToolTipText("");
        mSearchCoursesBtn.setAlignmentY(0.0F);
        mSearchCoursesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mSearchCoursesBtn.setFocusCycleRoot(true);
        mSearchCoursesBtn.setIconTextGap(0);
        mSearchCoursesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSearchCoursesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mSearchCoursesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 175, 28));

        mEditCourseBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        mEditCourseBtn.setForeground(new java.awt.Color(0, 102, 153));
        mEditCourseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsync/images/5.png"))); // NOI18N
        mEditCourseBtn.setText("Edit Course");
        mEditCourseBtn.setAlignmentY(0.0F);
        mEditCourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mEditCourseBtn.setFocusCycleRoot(true);
        mEditCourseBtn.setIconTextGap(0);
        mEditCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEditCourseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mEditCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 175, 28));

        mInputCourseBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        mInputCourseBtn.setForeground(new java.awt.Color(0, 102, 153));
        mInputCourseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classsync/images/Untitled design (6).png"))); // NOI18N
        mInputCourseBtn.setText("Input Course");
        mInputCourseBtn.setAlignmentY(0.0F);
        mInputCourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mInputCourseBtn.setFocusCycleRoot(true);
        mInputCourseBtn.setIconTextGap(2);
        mInputCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInputCourseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mInputCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 175, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSignOutBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mSignOutBtnStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mSignOutBtnStateChanged

    private void mSignOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSignOutBtnActionPerformed
        //Gets the current window location
        int currentX = getLocation().x;
        int currentY = getLocation().y;
        
        //Creates a new logic frame, set its location, makes it visible, and disposes current frame.
        loginjf loginFrame = new loginjf();
        loginFrame.setLocation(currentX, currentY);
        loginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_mSignOutBtnActionPerformed

    private void mInputCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInputCourseBtnActionPerformed
        //Gets the current window location
        int currentX = getLocation().x;
        int currentY = getLocation().y;
        
        //Creates a new logic frame, set its location, makes it visible, and disposes current frame.
        inputCoursesjf inputFrame = new inputCoursesjf(openAcc);
        inputFrame.setLocation(currentX, currentY);
        inputFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_mInputCourseBtnActionPerformed

    private void mViewCoursesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mViewCoursesBtnActionPerformed
        //Gets the current window location
        int currentX = getLocation().x;
        int currentY = getLocation().y;
        
        //Creates a new logic frame, set its location, makes it visible, and disposes current frame.
        viewCoursesjf viewFrame = new viewCoursesjf(openAcc);
        viewFrame.setLocation(currentX, currentY);
        viewFrame.setVisible(true); 
        dispose();
    }//GEN-LAST:event_mViewCoursesBtnActionPerformed

    private void mSearchCoursesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSearchCoursesBtnActionPerformed
        //Gets the current window location
        int currentX = getLocation().x;
        int currentY = getLocation().y;
        
        //Creates a new logic frame, set its location, makes it visible, and disposes current frame.
        searchCoursejf searchFrame = new searchCoursejf(openAcc);
        searchFrame.setLocation(currentX, currentY);
        searchFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_mSearchCoursesBtnActionPerformed

    private void mEditCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEditCourseBtnActionPerformed
        //Gets the current window location
        int currentX = getLocation().x;
        int currentY = getLocation().y;
        
        //Creates a new logic frame, set its location, makes it visible, and disposes current frame.
        editCoursejf editFrame = new editCoursejf(openAcc);
        editFrame.setLocation(currentX, currentY);
        editFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_mEditCourseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmenujf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmenujf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmenujf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenujf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenujf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton mEditCourseBtn;
    private javax.swing.JButton mInputCourseBtn;
    private javax.swing.JButton mSearchCoursesBtn;
    private javax.swing.JButton mSignOutBtn;
    private javax.swing.JButton mViewCoursesBtn;
    // End of variables declaration//GEN-END:variables
}
